### ISSUE TITLE
GCS to GCS relationship possible?

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/cloudsync#105]
Page: [Preparing the source and target](https://docs.netapp.com/us-en/cloudsync/reference_sync_requirements.html)

It is possible to create a GCS (source) to GCS (target) repository in the service but it is missing from this page.

**Comment by phoebegoh** [comment]
![image](https://user-images.githubusercontent.com/2746488/83882933-c8e53000-a710-11ea-8a54-f02c3740be60.png)

**Comment by netapp-bcammett** [comment]
Hi Phoebe,

As always, thank you for your feedback on the docs! I updated the page to include Google Cloud Storage to Google Cloud Storage.

Thanks again,
Ben
