### ISSUE TITLE
Cloud Sync - Source permissions

### ISSUE THREAD

**Issue by netapp-zbrezovec** [NetAppDocs/cloudsync#115]
Page: [Preparing the source and target](https://docs.netapp.com/us-en/cloudsync/reference_sync_requirements.html)

@netapp-bcammett 

what are the permission/rights requirements on the source of Cloud Sync relationship? Is read/list sufficient? This is related to Snapmirror destination, used as Clod Sync source.

Thank you.

**Comment by netapp-bcammett** [comment]
Hi there,

Thanks for submitting this issue. Can you please provide a little more information:

- What is the source in the sync relationship?
- What is the target in the sync relationship?

![image](https://user-images.githubusercontent.com/18287750/87940608-e1629d00-ca67-11ea-94db-18ae912e5ccd.png)

**Comment by netapp-zbrezovec** [comment]
Hi,

  *   What is the source in the sync relationship? Snapmirror destination
  *   What is the target in the sync relationship? Azure
Since the source for Cloud Sync (Snapmirror destination) is read only, we need information if this is valid for Cloud Sync relationship.
Thank you.
Z.

**Comment by netapp-bcammett** [comment]
Thank you. I've sent a question off to the product team to find the answer. I'll let you know if any additional information is needed to answer your question.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
I received confirmation that “read/list” permissions are sufficient for the SnapMirror source in the sync relationship.

Please let me know if you have any other questions. I'll leave this issue open until I incorporate that information into the documentation (should be later this week).

**Comment by netapp-zbrezovec** [comment]
Hi Ben,

great, thank you for the confirmation.
