### ISSUE TITLE
Clarify Proxy support

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloudsync#127]
Page: [Cloud Sync technical FAQ](https://docs.netapp.com/us-en/cloudsync/faq.html)

In the FAQ the following is stated:
"Data brokers require internet access. We don’t support a proxy server when deploying the data broker in Azure or in Google Cloud Platform."

However the latest release notes from November 1 state this:
"When you create a data broker, Cloud Sync now enables you to specify a proxy server for the data broker."

Is the FAQ still valid that proxy cannot be used for data brokers in Azure and GCP?  If so I'd suggest updating the release notes to clarify that proxy support is only for on-prem or AWS data broker deployment.

**Comment by netapp-bcammett** [comment]
Good catch. I updated the FAQ by removing that question since there the proxy limitation is no longer valid.
