### ISSUE TITLE
CloudSync Encryption support with proxy servers

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloudsync#129]
Page: [Syncing NFS data using data-in-flight encryption](https://docs.netapp.com/us-en/cloudsync/task_nfs_encryption.html)

For data-in-flight encryption for NFS to NFS (or ANF to ANF) relationships is it supported to use proxies for the two data brokers?  (In other words if I specify proxies for both data brokers will the TLS traffic going over 443 also go through the proxy, or will only the required internet endpoints for CloudSync command and control go over the proxy?

**Comment by netapp-bcammett** [comment]
Good question. I've forwarded it off to my contacts to find the answer. I will let you know what the answer is and then update the docs accordingly.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Mike,

I confirmed the following with my contacts:

"Cloud Sync supports proxy servers with or without basic authentication. If you specify a proxy server when you deploy a data broker, all HTTP traffic from the data broker is routed through the proxy. Note that non-HTTP traffic such as NFS or SMB can’t be routed through a proxy server.

The only proxy server limitation is when using data-in-flight encryption with an NFS or Azure NetApp Files sync relationship. The encrypted data is sent over HTTPS and isn’t routable through a proxy server."

Please let me know if anything isn't clear. I'll update the docs with this info.

Sorry for the delay--I was off last week for the US Thanksgiving holiday.

Regards,
Ben

**Comment by mimitche** [comment]
Hi Ben-

Thanks for the update.  That generally makes sense... although the use of "HTTP" is the first paragraph could lead to further confusion.  According to https://docs.netapp.com/us-en/cloudsync/reference_endpoints.html, CloudSync does not communicate over HTTP (port 80) at all.  All of the communication to endpoints happens over HTTPS (443) only.  If "HTTP" in the first paragraph is changed to "HTTPS" then it makes much more sense.

Thanks,
Mike

**Comment by netapp-bcammett** [comment]
Mike,

I received confirmation that all HTTP and HTTPS traffic is routed through the proxy. Update shown below.

"Cloud Sync supports proxy servers with or without basic authentication. If you specify a proxy server when you deploy a data broker, all HTTP **and HTTPS** traffic from the data broker is routed through the proxy. Note that non-HTTP traffic such as NFS or SMB can’t be routed through a proxy server.

The only proxy server limitation is when using data-in-flight encryption with an NFS or Azure NetApp Files sync relationship. The encrypted data is sent over HTTPS and isn’t routable through a proxy server."

Please let me know if anything else is unclear. Thanks!

**Comment by mimitche** [comment]
Looks good, thanks!

**Comment by netapp-bcammett** [comment]
The information about proxies was added to the FAQ:
https://docs.netapp.com/us-en/cloudsync/faq.html#networking
