### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/cloudsync#134]
Hi, There are couple of links used in the below page thats not working.

https://docs.netapp.com/us-en/cloudsync/task_managing_data_brokers.html

First link is under title "Determining the number of data brokers"

URL: https://docs.netapp.com/us-en/cloudsync/faq_sync.html#how-many-data-brokers-are-required 

Another is under Title  "Add a new data broker" there is topic named Learn how to create a new data broker when creating a sync relationship.

URL:https://docs.netapp.com/us-en/cloudsync/task_sync_creating_relationships.html

**Comment by netapp-bcammett** [comment]
Hello,

Sorry about those broken links! That was my mistake, but I just fixed them.

Thank you for reaching out to help make our docs better.

Regards,
Ben
