### ISSUE TITLE
Clarify download location of Data Broker software for on-prem deployments

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/cloudsync#49]
Page: [Getting started with the Cloud Sync service](https://docs.netapp.com/us-en/cloudsync/task_getting_started.html)

* It's not clear where (and at what point) one can download Data Broker software. This part (" Cloud Sync guides you through the installation process when you create a sync relationship.") could be modified to say "Cloud Sync guides you through the installation process when you create a sync relationship, at which point an install script can be downloaded for a Data Broker VM configured by the user." or something along these lines). 

* Under Linux Host Requirements (same page) it says ": Red Hat Enterprise Linux 7 or CentOS 7 or Fedora" but https://cloud.netapp.com/cloud-sync-comparison lists only RHEL and CentOs (shouldn't that be CentOS) for On-Prem. So Fedora should be added (or removed) and maybe CentOS should be written differently.

Both of these are necessary in order to prepare for DIY Data Broker installation.
Cloud Sync user does not always manage VI and/or network. In such cases they need to apply for a VM and sometimes provide DataBroker install script in advance, to make sure the VM has all OS dependencies and can download and deploy.

**Comment by netapp-bcammett** [comment]
Thank you for your feedback. I made two changes to address the comments in your first bullet:

![step 2](https://user-images.githubusercontent.com/18287750/53101916-aec21700-34f8-11e9-90d5-52d2010c6988.gif)

![linux host reqs](https://user-images.githubusercontent.com/18287750/53101923-b386cb00-34f8-11e9-987b-a77c278e49bf.gif)

As for the comment in your second bullet, I will contact the appropriate team to add Fedora and correct CentOS.

Thanks again and let me know if you think any additional changes are required.
