### ISSUE TITLE
[Improvement] Add the input format for "Exclude File Extensions" when creating a relation

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloudsync#81]
In reference to:
Page: [Creating a sync relationship](https://docs.netapp.com/us-en/cloudsync/task_creating_relationships.html)

For the users that refer to relationship creation "Exclude File Extensions" portion, would be helpful to add the format in which the input is expected.
   Example: txt; doc

This avoids possible try&error&recreation of relationship as there is no hint explaining if dot is expected and how to add several extensions (.txt? or txt?; accepts wild characters or not?; how to write multiple extensions (separator)?, etc )

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Thank you for providing this feedback. I updated the page by adding an explanation and a short video. Please take a look and let me know if you think any additional changes are needed.

Thanks again,
Ben

**Comment by gabrieltokyo** [comment]
Thank you. The improvement is great.
