### ISSUE TITLE
CentOS version unclear

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloudsync#91]
Page: [Copying ACLs between SMB shares](https://docs.netapp.com/us-en/cloudsync/task_copying_acls.html)

Can you clarify the CentOS version requirements for ACL copy?  On this page it says CentOS 7.0.  Is only this exact version compatible, or can it be any CentOS version as long as it's 7.0 or greater?

**Comment by netapp-bcammett** [comment]
Hi there,

It is 7.0 only. No other versions are supported.

I updated the page to clarify this. I added the following:

"CentOS 7.0 is the only version supported with this feature. You can’t use this feature with a CentOS host running a version greater than 7.0."

Thank you for your feedback.

Regards,
Ben
