### ISSUE TITLE
Data Broker Deletion Procedures

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloudsync#93]
Page: [Cloud Sync Documentation](https://docs.netapp.com/us-en/cloudsync/index.html)

I'm in the middle of writing procedures for PS engagements that use CloudSync to migrate data into ANF instances.  At the very end we have cleanup procedures that includes (among other things) removing the data broker from the customer's Cloud Central account.  As far as I can tell the only way to delete a Data Broker listing in the CloudSync interface it to pretend I'm creating a new sync relationship, and then delete it on the "Data Broker" selection page.  Is there any other way to delete the data broker entry, and if so is it documented on CloudDocs?

**Comment by netapp-bcammett** [comment]
Hi there,

Yes, you are right: in the new relationship wizard, you can remove the data broker from the Data Broker page.

The other option is to use an API call: DELETE /data-brokers/{id}

![delete](https://user-images.githubusercontent.com/18287750/76229471-a23e5880-61f8-11ea-8fbc-fe245eff7e97.jpg)
